{
 "title": "dt2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GIT OPS (FluxCD) Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"flux-system/kustomize-controller\"} |= `<COHORT>-<TEAM>-<ENV>`"
    }
   ]
  },
  {
   "title": "Namespace Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{namespace=\"<COHORT>-<TEAM>-<ENV>\"}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Percentage of All Requests le 500 Milliseconds",
   "type": "timeseries",
   "description": "This uses the ingress-nginx logs",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": " sum( # request faster than 0.1 seconds\r\n  count_over_time({app=\"ingress-nginx\"} \r\n    !=\"/metric\" \r\n    | json  \r\n      |  __error__!=`JSONParserErr` \r\n      | host =`<COHORT><TEAM><ENV>-api.computerlab.online` \r\n      | upstream_status=~\"2[0-9]{2}\"  \r\n      | upstream_response_time <= 0.5\r\n  [1m])\r\n ) \r\n\r\n / # divided by\r\n\r\n  sum( # all request\r\n  count_over_time({app=\"ingress-nginx\"} \r\n    !=\"/metric\" \r\n    | json  \r\n      |  __error__!=`JSONParserErr` \r\n      | host =`<COHORT><TEAM><ENV>-api.computerlab.online` \r\n      | upstream_status=~\"2[0-9]{2}\"  \r\n  [1m])\r\n ) * 100 # make into percentage\r\n "
    }
   ]
  },
  {
   "title": "Percentage of Trade Requests le 750 Milliseconds",
   "type": "timeseries",
   "description": "This uses the ingress-nginx logs",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": " sum( # request faster than 0.1 seconds\r\n  count_over_time({app=\"ingress-nginx\"} \r\n    !=\"/metric\" \r\n    | json  \r\n      |  __error__!=`JSONParserErr` \r\n      | host =`<COHORT><TEAM><ENV>-api.computerlab.online` \r\n      | request_uri =`/trade`\r\n      | upstream_status=~\"2[0-9]{2}\"  \r\n      | upstream_response_time <= 0.75\r\n  [1m])\r\n ) \r\n\r\n / # divided by\r\n\r\n  sum( # all request\r\n  count_over_time({app=\"ingress-nginx\"} \r\n    !=\"/metric\" \r\n    | json  \r\n      |  __error__!=`JSONParserErr` \r\n      | host =`<COHORT><TEAM><ENV>-api.computerlab.online`\r\n      | request_uri =`/trade`\r\n      | upstream_status=~\"2[0-9]{2}\"  \r\n  [1m])\r\n ) * 100 # make into percentage\r\n "
    }
   ]
  },
  {
   "title": "Avg Milliseconds / Endpoint",
   "type": "timeseries",
   "description": "This uses the ingress-nginx logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"ingress-nginx\"} \r\n    !=\"/metric\" \r\n    | json\r\n        # remove json parsing errors  \r\n      |  __error__!=`JSONParserErr` \r\n      | host =`<COHORT><TEAM><ENV>-api.computerlab.online`\r\n      # successfull request \r\n      | upstream_status=~\"(2|3)[0-9]{2}\"\r\n      # create a field named path to group by  \r\n      | regexp `request_uri[\"\\s:]+(?P<path>[\\/]+[a-z_]+).*` # create field named path\r\n      # The unwrap allows us to specify the field and time range for our average\r\n      | unwrap upstream_response_time[1m])\r\n ) by (path) * 1000\r\n ",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Min and Max Milliseconds / Endpoint / Minute",
   "type": "timeseries",
   "description": "This uses the ingress-nginx logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"ingress-nginx\"} \r\n    !=\"/metric\" \r\n    | json\r\n        # remove json parsing errors  \r\n      |  __error__!=`JSONParserErr` \r\n      | host =`<COHORT><TEAM><ENV>-api.computerlab.online`\r\n      # successfull request \r\n      | upstream_status=~\"(2|3)[0-9]{2}\"\r\n      # create a field named path to group by  \r\n      | regexp `request_uri[\"\\s:]+(?P<path>[\\/]+[a-z_]+).*` # create field named path\r\n      # The unwrap allows us to specify the field and time range for our average\r\n      | unwrap upstream_response_time[1m])\r\n ) by (path) * 1000\r\n ",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "min(min_over_time({app=\"ingress-nginx\"} \r\n    !=\"/metric\" \r\n    | json\r\n        # remove json parsing errors  \r\n      |  __error__!=`JSONParserErr` \r\n      | host =`<COHORT><TEAM><ENV>-api.computerlab.online`\r\n      # successfull request \r\n      | upstream_status=~\"(2|3)[0-9]{2}\"\r\n      # create a field named path to group by  \r\n      | regexp `request_uri[\"\\s:]+(?P<path>[\\/]+[a-z_]+).*` # create field named path\r\n      # The unwrap allows us to specify the field and time range for our average\r\n      | unwrap upstream_response_time[1m])\r\n ) by (path) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of Requests le 500 milliseconds ",
   "type": "timeseries",
   "description": "This uses the metrics from our app",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_request_duration_seconds_bucket{namespace='<COHORT>-<TEAM>-<ENV>',handler!~\"(none|/metrics)\",le=\"0.5\"}[$__rate_interval])) / sum by (handler) (rate(http_request_duration_seconds_bucket{handler!~\"(none|/metrics)\",le=\"+Inf\",namespace=\"<COHORT>-<TEAM>-<ENV>\"}[$__rate_interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "MYSQL Up",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{namespace=\"c999-rickyp-<ENV>\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins Health Score",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_health_check_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All 2xx Request / Errors (not 4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 26 },
   "targets": [
    {
     "expr": "sum by (handler) (http_requests_total{namespace=\"<COHORT>-<TEAM>-<ENV>\", status=~\"(2|3).*\", handler!~\"(metrics|docs)\"})\r\n/\r\nsum by (handler) (http_requests_total{namespace=\"<COHORT>-<TEAM>-<ENV>\", status!~\"4.*\", handler!~\"(/metrics|/docs)\"})\r\n*100",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Site Probe Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\",namespace=\"<COHORT>-<TEAM>-<ENV>\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Percent of Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"<COHORT>-<TEAM>-<ENV>\", status=~\"4.*\"}[1m]))\r\n/\r\nsum(rate(http_requests_total{namespace=\"<COHORT>-<TEAM>-<ENV>\"}[1m]))\r\n*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Available Replicas Per Deployment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{namespace=\"<COHORT>-<TEAM>-<ENV>\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "Container Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (container)( rate(container_cpu_usage_seconds_total # metric\r\n  {\r\n    namespace=\"<COHORT>-<TEAM>-<ENV>\",\r\n    container=~`orderbook.*`\r\n  }[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 35 },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_memory_working_set_bytes{namespace=\"<COHORT>-<TEAM>-<ENV>\", \r\n  container=~`orderbook.*`}[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Number of Requests  / Endpoint / Minute",
   "type": "barchart",
   "description": "This uses our application logs.",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "# uses app logs\r\nsum(count_over_time({namespace=\"<COHORT>-<TEAM>-<ENV>\"} |~ `\"path\": \"/(trade|holdings|docs|login|trade|all_orders|stock_quote|stocklist).*\"` | json [$__interval] )) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Number of Mysql Connections",
   "type": "graph",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_connected{namespace=\"<COHORT>-<TEAM>-<ENV>\"}",
     "legendFormat": "Peak Threads Connected"
    }
   ]
  },
  {
   "title": "Percentage of Jenkin Builds Success vs Fail",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count_total{jenkins_job=\"<COHORT><TEAM>-promote\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "default_jenkins_builds_failed_build_count_total{jenkins_job=\"<COHORT><TEAM>-promote\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of Sucessful Jenkins Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count_total{jenkins_job=\"<COHORT><TEAM>-promote\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}