apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: <COHORT><TEAM>dev<API>
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: production-support-course
  filterTags:
    pattern: '^<COHORT><TEAM><API>-dev-(?P<ts>.*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc